import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>farmersmarketV9</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon -.ico" />
      </Head>



    <main  className="bg-black min-h-screen flex m-w-[1500px] mx-auto">
        {/* Sidebar */}
        <Sidebar />

          {/* Feed  */}
            <Feed />

            {/* Widgets */}
              
              
              {/*Modal */}

    </main>
      
    </div>
  )
}
